STAX/Models/SpecMaster.cs
using System.Collections.Generic;

namespace STAX.Models
{
    /// <summary>
    /// Holds data related to a spec in whole
    /// </summary>
    public class SpecMaster
    {
        //Attributes
        public enum SpecStatusTypes : int
        {
            In_Spec_Build,
            Await_Development_Review,
            In_Development_Review,
            In_Development_Process,
            Complete,
            Canned
        }
        public int ID { get; set; }
        public string CrNumber { get; set; }
        public string SpecName { get; set; }
        public string SpecDesc { get; set; }
        public string SpecNotes { get; set; }

		public User CreatorUser { get; set; }

        public bool SpecHidden { get; set; }
        public SpecStatusTypes SpecStatus { get; set; }
		
        public ICollection<SpecRtpItem> SpecItems { get; set; }
        public ICollection<SpecUpdateItem> SpecUpdateItems { get; set; }

        //Constructor
        public SpecMaster()
        {

        }
    }
}

STAX/Controllers/SpecMasterController.cs
using System.Linq;
using System.Collections.Generic;
using System.Configuration;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using STAX.Models;
using STAX.Data;
using STAX.JSON;
using Microsoft.EntityFrameworkCore;
using System;
using Newtonsoft.Json;

namespace STAX.Controllers
{
    public class SpecMasterController : Controller
    {
        //Attributes
        private readonly StaxContext _context;

        //Constructor
        public SpecMasterController(StaxContext context)
        {
            _context = context;
        }

        /// <summary>
        /// All SpecMaster items listing.
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            ViewBag.AllSpecs = _context.SpecMasterCollection
                .Include(specMaster => specMaster.CreatorUser)
                .Where(specMaster => !specMaster.SpecHidden)
                .ToList();
            return View(_context.UserCollection
                .Include(user => user.UserPermissions)
                .Single(user => user.WindowsDirRef == User.Identity.Name));
        }

        /// <summary>
        /// Details for a specific SpecMaster (View a spec).
        /// </summary>
        /// <param name="thisSpecMasterID"></param>
        /// <returns></returns>
        public async Task<IActionResult> ViewSpec(int thisSpecMasterID)
        {
            //Fetch spec and associations; fetch user
            SpecMaster thisSpecMaster = await _context.SpecMasterCollection
                .Include(specMaster => specMaster.CreatorUser)
                .Include(specMaster => specMaster.SpecItems)
                .Include(specMaster => specMaster.SpecUpdateItems)
                .Where(specMaster => specMaster.ID == thisSpecMasterID)
                .SingleAsync();
            User thisUser = await _context.UserCollection.SingleAsync(user => user.WindowsDirRef == User.Identity.Name.ToUpper());

            //Return
            if (thisSpecMaster.CreatorUser.ID == thisUser.ID
                || thisUser.UserPermissions.EditSpecLevel == UserPermissions.EditSpecLevels.Edit_All)
            {
                ViewBag.CanEdit = true;
            }
            else { ViewBag.CanEdit = false; }
            return View(thisSpecMaster);
        }

        /// <summary>
        /// Create a new master spec item.
        /// </summary>
        /// <param name="thisCrNumber"></param>
        /// <param name="thisSpecName"></param>
        /// <param name="thisSpecDesk"></param>
        /// <returns></returns>
        public async Task<IActionResult> CreateSpec(string thisCrNumber, string thisSpecName, string thisSpecDesk)
        {
            //Fetch the current user
            User thisUser = await _context.UserCollection
                .Include(user => user.UserPreferences)
                .SingleAsync(user => user.WindowsDirRef == User.Identity.Name);

            //Spec creation process
            #region Spec Creation

            //Create spec
            _context.SpecMasterCollection.Add(new SpecMaster {
                CrNumber = thisCrNumber,
                SpecName = thisSpecName,
                SpecDesc = thisSpecDesk,
                CreatorUser = thisUser,
                SpecHidden = false,
                SpecStatus = SpecMaster.SpecStatusTypes.In_Spec_Build
            });

            //Create spec update for creation process
            await _context.SaveChangesAsync();
            SpecMaster newlyAddedSpec = await _context.SpecMasterCollection.LastAsync();
            await _context.SpecUpdateCollection.AddAsync(new SpecUpdateItem
            {
                Content = String.Format("Spec No #{0} was created on {1}, at {2} by {3}:",
                    newlyAddedSpec.ID,
                    DateTime.Now.ToShortDateString(),
                    DateTime.Now.ToShortTimeString(),
                    String.Format("{0} {1}", thisUser.FirstName, thisUser.SecondName)),
                ChangeLog = "Spec was created.",
                CreationDate = DateTime.Now,
                User = thisUser,
                SpecMaster = newlyAddedSpec
            });

            #endregion

            //Send confirmation message, if enabled by user prefs
            if (!thisUser.UserPreferences.DisableMessages)
            {
                _context.MessageCollection.Add(new Message
                {
                    MessageTitle = "Success! Your new Spec is ready.",
                    MessageContent = "Congratulations - be sure to save your changes regularly!",
                    MessageExpires = true,
                    MessageSent = DateTime.Now,
                    MessageVisible = true,
                    SystemMessage = true,
                    SenderUser = await _context.UserCollection.FindAsync(1),
                    ReceiverUser = await _context.UserCollection.Where(user => user.WindowsDirRef == User.Identity.Name).SingleAsync()
                });
            }

            //Return
            await _context.SaveChangesAsync();
            return RedirectToAction("ViewSpec", "SpecMaster", new { thisSpecMasterID = _context.SpecMasterCollection.Last().ID });
        }

        /// <summary>
        /// Create/Update and save all spec RTP items iteratively; AJAX powered.
        /// </summary>
        /// <param name="specID"></param>
        /// <param name="specItemIDs"></param>
        /// <param name="specItemTypes"></param>
        /// <param name="specItemTexts"></param>
        /// <param name="specItemOptions"></param>
        /// <param name="specItemDeleted"></param>
        /// <param name="specNotes"></param>
        /// <returns></returns>
        public async Task<JsonResult> SaveAllExisting(int specID,
            int[] specItemIDs,
            int[]specItemTypes,
            String[] specItemTexts,
            int[] specItemOptions,
            int[] specItemDeleted,
            String specNotes,
            int specStatus,
            String specName,
            String specDesc)
        {
            //Initialize response object
            JsonActionResponse response;
            try
            {
                response = new JsonActionResponse(true);

                //Changelog statistics
                int numberItemsAdded = 0;
                int numberItemsRemoved = 0;
                int numberItemsUpdated = 0;

                //Create/Update/Delete RTP items
                for (int i = 0; i < specItemIDs.Length; i++)
                {
                    //New RtpItems initialized with ID attribute -1
                    bool isNewItem = specItemIDs[i] == -1;

                    //Item does not exist - Create new item
                    #region New RTP item

                    if (isNewItem)
                    {
                        //Item does not already exist, create with params and add to database
                        await _context.AddAsync(new SpecRtpItem
                        {
                            ItemOrderNumber = i,
                            ItemType = specItemTypes[i],
                            ItemText = specItemTexts[i],
                            ItemOption = specItemOptions[i],
                            User = await _context.UserCollection.Where(user => user.WindowsDirRef == User.Identity.Name).SingleAsync(),
                            SpecMaster = await _context.SpecMasterCollection.FindAsync(specID)
                        });
                        numberItemsAdded++;
                    }

                    #endregion

                    //Item does exist - Update / Delete existing item
                    #region Existing RTP item

                    else
                    {
                        //Item already exists; update or delete accordingly
                        if (specItemDeleted[i] == 1)
                        {
                            //Delete
                            _context.SpecRtpItemCollection.Remove(_context.SpecRtpItemCollection.Find(specItemIDs[i]));
                            numberItemsRemoved++;
                        }
                        else
                        {
                            //Update
                            SpecRtpItem thisSpecRtpItem = await _context.SpecRtpItemCollection.FindAsync(specItemIDs[i]);
                            thisSpecRtpItem.Update(i, specItemTypes[i], specItemTexts[i], specItemOptions[i]);
                            _context.SpecRtpItemCollection.Update(thisSpecRtpItem);

                            //Increment updated count only if item has changed
                            if (thisSpecRtpItem.ItemOrderNumber != i
                                    || thisSpecRtpItem.ItemType != specItemTypes[i]
                                    || thisSpecRtpItem.ItemText != specItemTexts[i]
                                    || thisSpecRtpItem.ItemOption != specItemOptions[i])
                            {
                                numberItemsUpdated++;
                            }           
                        }
                    }

                    #endregion
                }

                #region SpecMaster update

                //Fetch SpecMaster and current User
                SpecMaster thisSpecMaster = await _context.SpecMasterCollection.FindAsync(specID);
                User thisUser = await _context.UserCollection.Where(user => user.WindowsDirRef == User.Identity.Name).SingleAsync();

                //Build changelog
                #region Changelog

                String changeLog = "";
                String[] statusRef =
                {
                    "Under Construction",
                    "Awaiting Review",
                    "Under Review",
                    "In Development",
                    "Completed",
                    "Canned"
                };

                //Determine changelog content

STAX/ViewComponents/CreateSpecViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using STAX.Data;
using STAX.Models;

namespace STAX.ViewComponents
{
    public class CreateSpecViewComponent : ViewComponent
    {
        private readonly StaxContext _context;

        //Constructor
        public CreateSpecViewComponent(StaxContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Provide data for messages modal.
        /// </summary>
        /// <returns></returns>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

STAX/ViewComponents/SelectItemsViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using STAX.Data;
using STAX.Models;

namespace STAX.ViewComponents
{
    public class SelectItemsViewComponent : ViewComponent
    {
        //Constructor
        public SelectItemsViewComponent()
        {

        }

        /// <summary>
        /// Render options according to type.
        /// </summary>
        /// <returns></returns>
        public async Task<IViewComponentResult> InvokeAsync(int type)
        {
            ViewBag.Type = type;
            return View();
        }
    }
}

STAX/Views/SpecMaster/Index.cshtml
@model STAX.Models.User

@{
    ViewData["Title"] = "All Specs";
    var allSpecMasters = (List<STAX.Models.SpecMaster>)ViewBag.AllSpecs;
}

@section Scripts {
    <script type="text/javascript" src="~/js/SpecIndex.js" asp-append-version="true"></script>
}

@section Styles {
    <link rel="stylesheet" href="~/css/specindex.css" asp-append-version="true" />
}

<!--Spec creation modal-->
<div class="modal_back" js-modalVal="2">
    @await Component.InvokeAsync("CreateSpec");
</div>

<p class="index_banner">All Specs</p>

<!--Main Options-->
@if (Model.UserPermissions.CreateSpecLevel != STAX.Models.UserPermissions.CreateSpecLevels.Create_None
    || (Model.UserPermissions.CreateSpecLevel == STAX.Models.UserPermissions.CreateSpecLevels.Create_Capped && Model.UserSpecs.Count < 5))
{
    <div class="index_option" onclick="ToggleModal(2)" title="Create a new Spec of your own.">New Spec</div>
}
<input id="index_search" placeholder="Search." value="" title="Find a Spec using your input." />
<br>

<!--Search radio buttons-->
<table id="index_searchGrouper">
    <tr>
        <td><p>Search By Number</p></td>
        <td><p>Search by CR</p></td>
        <td><p>Search by Title</p></td>
        <td><p>Search by Desc</p></td>
    </tr>
    <tr>
        <td><div js-attrVal="0" class="index_searchOption activeSearch" onclick="SwitchSearchAttr(this)"
                 title="Filter Specs by Spec number."></div></td>
        <td><div js-attrVal="1" class="index_searchOption" onclick="SwitchSearchAttr(this)" 
                 title="Filter Specs by linked CR number"></div></td>
        <td><div js-attrVal="2" class="index_searchOption" onclick="SwitchSearchAttr(this)" 
                 title="Filter Specs by title."></div></td>
        <td><div js-attrVal="3" class="index_searchOption" onclick="SwitchSearchAttr(this)" 
                 title="Filter Specs by description."></div></td>
    </tr>
</table>

<!--Spec listing-->
<table class="index_table">
    <thead>
        <tr class="leadRow">
            <th>Spec Number</th>
            <th>Spec CR</th>
            <th>Title</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Status</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        @foreach (STAX.Models.SpecMaster thisSpecMaster in allSpecMasters)
        {
            <tr>
                <td js-attrVal="0">@thisSpecMaster.ID</td>
                <td js-attrVal="1">@thisSpecMaster.CrNumber</td>
                <td js-attrVal="2">@thisSpecMaster.SpecName</td>
                <td js-attrVal="3">
                    <div class="index_tableDesc">
                        @thisSpecMaster.SpecDesc
                    </div>
                </td>
                @{String thisActive = thisSpecMaster.CreatorUser.ID == Model.ID ? "enabled" : "disabled";}
                <td>
                    <i class="fas fa-star @thisActive" title="@(thisActive == "enabled" ? "You own this Spec!" : "You do not own this Spec.")"></i>
                </td>
                <td>
                    <div class="index_tablePill @String.Format("status{0}", (int)thisSpecMaster.SpecStatus)">
                        @switch ((int)thisSpecMaster.SpecStatus)
                        {
                            case 0:<p title="This Spec is currently being built.">Construction</p>
                                break;
                            case 1: <p title="This Spec is currently awaiting review by the Development Team.">Await Review</p>
                                break;
                            case 2: <p title="This Spec is currently being reviewed by the Development Team.">In Review</p>
                                break;
                            case 3: <p title="This Spec has passed review and is being used for the build.">In Dev</p>
                                break;
                            case 4: <p title="This Spec has passed review and has been built.">Complete</p>
                                break;
                            case 5: <p title="This Spec is no longer required and has been canned.">Canned</p>
                                break;
                            default: <p title="The status of this Spec is not currently known.">Unknown</p>
                                break;
                        }
                    </div>
                </td>
                <td class="specActive">
                    <!--Link to ViewSpec for this Spec-->
                    <a asp-controller="SpecMaster" asp-action="ViewSpec" asp-route-thisSpecMasterID="@thisSpecMaster.ID" title="View this Spec.">
                        <i class="fas fa-external-link-alt"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

STAX/Views/SpecMaster/ViewSpec.cshtml
@model STAX.Models.SpecMaster

<!--Page vars-->
@{
    //Page title
    ViewData["Title"] = String.Format("RTP Spec | {0}", Model.CrNumber);
    bool canEdit = ViewBag.CanEdit;

    //Edit controls, variables
    var itemEnabled = canEdit ? "enabled" : "disabled";
    String[] enabledTitle =
    {
        "Add a condition; use these to determine actions.",
        "Add an operator; use these to combine conditions.",
        "Add a calculation; use these to describe complex logic.",
        "Add a lookup; use these to describe table lookups.",
        "Add an action; use these as a consequence of conditions or operators.",
        "Add a freeform; use these to describe anything not covered by the above.",
        "Add a spacer; use these to make your spec easier to read.",
        "Use this to toggle delete mode (double click to remove items).",
        "Use this to save all changes to your spec (double click to confirm).",
        "Use this to reset your spec completely (double click to confirm).",
        "Add notes to your spec here.",
        "Name your Spec here.",
        "Describe your Spec here."
     };
    String disabledTitle = "You do not have permissions to edit this Spec.";

    //Spec status value
    int statusVal = (int)Model.SpecStatus;
}

@section Scripts {
    <script type="text/javascript" src="~/js/SpecMaster.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" asp-append-version="true"></script>
}

@section Styles {
    <link rel="stylesheet" href="~/css/SpecMaster.css" asp-append-version="true" />
}

<!--Updates modal-->
<div class="modal_back" js-modalVal="3">
    @await Component.InvokeAsync("SpecUpdates", Model.ID)
</div>

<!--Spec CR, description-->
<div id="specmaster_titleBanner">
    <p>@String.Format("{0} | {1} {2}", Model.CrNumber, Model.CreatorUser.FirstName, Model.CreatorUser.SecondName)</p>

    <!--Spec name, description-->
    <input id="specmaster_specName" class="@itemEnabled" type="text" value="@Model.SpecName" placeholder="Enter your Spec name here." onchange="SetUnsaved()"
           title="@(canEdit ? enabledTitle[11] : disabledTitle)"/>
    <input id="specmaster_specDesc" class="@itemEnabled" type="text" value="@Model.SpecDesc" placeholder="Enter your Spec description here." onchange="SetUnsaved()"
           title="@(canEdit ? enabledTitle[12] : disabledTitle)"/>
</div>

<!--Spec status-->
<div id="specmaster_statusPill" class="@String.Format("status{0}", (int)Model.SpecStatus)">
    @{
        switch ((int)Model.SpecStatus)
        {
            case 0: <p title="This Spec is currently being built.">Under Construction</p>
                break;
            case 1: <p title="This Spec is currently awaiting review by the Development Team.">Awaiting Review</p>
                break;
            case 2: <p title="This Spec is currently being reviewed by the Development Team">Under Review</p>
                break;
            case 3: <p title="This Spec has passed review and is being used for the build.">In Development</p>
                break;
            case 4: <p title="This Spec has passed review and has been built.">Completed</p>
                break;
            case 5: <p title="This Spec is no longer required and has been canned.">Canned</p>
                break;
            default: <p title="The status of this Spec is not currently known.">Status Unknown</p>
                break;
        }
    }
</div>

<!--Options-->
<div id="specmaster_menuItems">

    <!--Save status-->
    <p id="specmaster_lastSaved" class="menuLabel">Unmodified</p>

    <!--Spec status-->
    <select id="specmaster_statusType" class="menuSelect" onchange="SetUnsaved()" asp-for="@statusVal"
            title="@(canEdit ? "Change the status of this Spec." : disabledTitle)">
        <option value="0" title="Select this if you are still building your spec.">Under Construction</option>
        <option value="1" title="Select this if you have finished building your spec.">Awaiting Review</option>
        <option value="2" title="Select this if you are reviewing this spec.">Under Review</option>
        <option value="3" title="Select this if you are developing this spec.">In Development</option>
        <option value="4" title="Select this if you have completed the build for this spec.">Completed</option>
        <option value="5" title="Select this if this spec is no longer required.">Canned</option>
    </select>

    <!--Add item options-->
    <div class="menuOption condition @itemEnabled" ondblclick="AddSpecItem(0, this)"
         title="@(canEdit ? enabledTitle[0] : disabledTitle)">Add Condition</div>

    <div class="menuOption operator @itemEnabled" ondblclick="AddSpecItem(1, this)"
         title="@(canEdit ? enabledTitle[1] : disabledTitle)">Add Operator</div>

    <div class="menuOption calculation @itemEnabled" ondblclick="AddSpecItem(2, this)"
         title="@(canEdit ? enabledTitle[2] : disabledTitle)">Add Calculation</div>

    <div class="menuOption lookup @itemEnabled" ondblclick="AddSpecItem(3, this)"
         title="@(canEdit ? enabledTitle[3] : disabledTitle)">Add Lookup</div>

    <div class="menuOption action @itemEnabled" ondblclick="AddSpecItem(4, this)"
         title="@(canEdit ? enabledTitle[4] : disabledTitle)">Add Action</div>

    <div class="menuOption freeform @itemEnabled" ondblclick="AddSpecItem(5, this)"
         title="@(canEdit ? enabledTitle[5] : disabledTitle)">Add Freeform</div>

    <div class="menuOption spacer @itemEnabled" ondblclick="AddSpecItem(6, this)"
         title="@(canEdit ? enabledTitle[6] : disabledTitle)">Add Spacer</div>

    <!--Spec main options-->
    <div id="specmaster_toggleDelete" class="menuOption @itemEnabled" ondblclick="ToggleDelete(this)"
         title="@(canEdit ? enabledTitle[7] : disabledTitle)">Delete Mode OFF</div>

    <div class="menuOption @itemEnabled" ondblclick="Reset(this)"
         title="@(canEdit ? enabledTitle[9] : disabledTitle)">Delete All</div>

    <div class="menuOption @itemEnabled" ondblclick="SaveAll(this)"
         title="@(canEdit ? enabledTitle[8] : disabledTitle)">Save Changes</div>

    <div class="menuOption" ondblclick="ToggleModal(3)"
         title="View Spec Updates.">Updates Log</div>
</div>

<!--Spec items-->
<div id="specmaster_specContent">
    <ul id="specmaster_specList" class="sortable" js-specID="@Model.ID" ul class="sortable">
        @{
            if (Model.SpecItems != null) //Only proceed if spec has defined item collection
            {
                //Sort the items and add to the list
                List<STAX.Models.SpecRtpItem> thisSpecContentsSorted = (List<STAX.Models.SpecRtpItem>)Model.SpecItems.OrderBy(specItem => specItem.ItemOrderNumber).ToList();
                foreach (STAX.Models.SpecRtpItem thisSpecRtpItem in thisSpecContentsSorted)
                {
                    //Determine appropriate RTP spec item
                    switch (thisSpecRtpItem.ItemType)
                    {
                        case 0: //Conditional item
                            <li class="specItem condition"
                                js-specItemID="@thisSpecRtpItem.ID" js-specItemType="0"
                                js-specItemText="@thisSpecRtpItem.ItemText" js-optionVal="@thisSpecRtpItem.ItemOption" js-isDeleted="0">
                                <select @itemEnabled>
                                    @await Component.InvokeAsync("SelectItems", 1)
                                </select>
                                <input type="text" value="@thisSpecRtpItem.ItemText" @itemEnabled />
                            </li>
                            break;

                        case 1: //Operator item
                            <li class="specItem operator"
                                js-specItemID="@thisSpecRtpItem.ID" js-specItemType="1"
                                js-specItemText="@thisSpecRtpItem.ItemText" js-optionVal="@thisSpecRtpItem.ItemOption" js-isDeleted="0">
                                <select class="centred" @itemEnabled>
                                    @await Component.InvokeAsync("SelectItems", 2)
                                </select>
                            </li>
                            break;

                        case 2: //Calculation item
                            <li class="specItem calculation"
                                js-specItemID="@thisSpecRtpItem.ID" js-specItemType="2"
                                js-specItemText="@thisSpecRtpItem.ItemText" js-optionVal="@thisSpecRtpItem.ItemOption" js-isDeleted="0">
                                <input class="centred" type="text" value="@thisSpecRtpItem.ItemText" @itemEnabled>
                            </li>
                            break;

                        case 3: //Lookup item
                            <li class="specItem lookup"
                                js-specItemID="@thisSpecRtpItem.ID" js-specItemType="3"
                                js-specItemText="@thisSpecRtpItem.ItemText" js-optionVal="@thisSpecRtpItem.ItemOption" js-isDeleted="0">
                                <input class="centred" type="text" value="@thisSpecRtpItem.ItemText" @itemEnabled>
                            </li>
                            break;

                        case 4: //Action item
                            <li class="specItem action"
                                js-specItemID="@thisSpecRtpItem.ID" js-specItemType="4"
                                js-specItemText="@thisSpecRtpItem.ItemText" js-optionVal="@thisSpecRtpItem.ItemOption" js-isDeleted="0">
                                <select class="centred" @itemEnabled>
                                    @await Component.InvokeAsync("SelectItems", 3)
                                </select>
                            </li>
                            break;

                        case 5: //Freeform item
                            <li class="specItem freeform"
                                js-specItemID="@thisSpecRtpItem.ID" js-specItemType="5"
                                js-specItemText="@thisSpecRtpItem.ItemText" js-optionVal="@thisSpecRtpItem.ItemOption" js-isDeleted="0">
                                <input class="centred" type="text" value="@thisSpecRtpItem.ItemText" @itemEnabled />
                            </li>
                            break;

                        case 6: //Spacer item
                            <li class="specItem spacer"
                                js-specItemID="@thisSpecRtpItem.ID" js-specItemType="6"
                                js-specItemText="@thisSpecRtpItem.ItemText" js-optionVal="@thisSpecRtpItem.ItemOption" js-isDeleted="0">
                            </li>
                            break;
                        default: //Error - item type outside range
                            <li class="specItem error"
                                js-specItemID="@thisSpecRtpItem.ID" js-specItemType="-1"
                                js-specItemText="@thisSpecRtpItem.ItemText" js-optionVal="@thisSpecRtpItem.ItemOption" js-isDeleted="0">
                                <p class="centred">An error occured loading this item: Please try again later.</p>
                            </li>
                            break;
                    }
                }
            }
        }
    </ul>
</div>

<!--Note text content-->
<div id="specmaster_notesContent" class="@itemEnabled" contenteditable="@canEdit.ToString().ToLower()" js-optionVal="0" onchange="SetUnsaved()"
     title="@(canEdit ? enabledTitle[10] : disabledTitle)">
    @Model.SpecNotes
</div>