STAX/Models/Message.cs
using System;

namespace STAX.Models
{
    /// <summary>
    /// Holds data for a message
    /// </summary>
    public class Message
    {
        //Attributes
        public int ID { get; set; }
		public String MessageTitle { get; set; }
        public String MessageContent { get; set; }
        public bool MessageExpires { get; set; }
        public DateTime MessageSent { get; set; }
        public bool MessageVisible { get; set; }
        public bool SystemMessage { get; set; }

        public User SenderUser { get; set; }
        public User ReceiverUser { get; set; }
        
        //Constructor
        public Message()
        {

        }

        /// <summary>
        /// Create message via clone.
        /// </summary>
        /// <param name="existingMessage"></param>
        public Message(Message existingMessage)
        {
            MessageTitle = existingMessage.MessageTitle;
            MessageContent = existingMessage.MessageContent;
            MessageExpires = false;
            MessageSent = existingMessage.MessageSent;
            MessageVisible = false;
            SystemMessage = true;
            SenderUser = existingMessage.SenderUser;
            ReceiverUser = existingMessage.ReceiverUser;
        }

        /// <summary>
        /// Returns whether this message has expired.
        /// </summary>
        /// <returns></returns>
        public bool GetMessageHasExpired()
        {
            if (!MessageExpires) { return false; }
            else if ((DateTime.Now.DayOfYear - MessageSent.DayOfYear) > 30)
            {
                return true;
            }
            return false;
        }

        /// <summary>
        /// Return the age of this message in days.
        /// </summary>
        /// <returns></returns>
        public int GetMessageAge()
        {
            return (DateTime.Now - MessageSent).Days;
        }

        /// <summary>
        /// Return formatted representation of the date this message will expire.
        /// </summary>
        /// <returns></returns>
        public String GetMessageExpiryDate()
        {
            if (!MessageExpires) { return "Never"; }
            else
            {
                return MessageSent.AddDays(30).ToString("dd MM yyyy");
            }
        }
    }
}

STAX/Controllers/MessageController.cs
using System.Diagnostics;
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using STAX.Models;
using STAX.Data;
using STAX.JSON;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;

namespace STAX.Controllers
{
    public class MessageController : Controller
    {
        //Attributes
        private readonly StaxContext _context;

        //Constructor
        public MessageController(StaxContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Create a message, add to DB
        /// </summary>
        /// <param name="thisMessageTitle"></param>
        /// <param name="thisMessageContent"></param>
        /// <param name="thisMessageExpires"></param>
        /// <param name="thisUserID"></param>
        /// <param name="thisTargetUserID"></param>
        /// <returns></returns>
        public async Task<JsonResult> SendMessage(String title,
            String content,
            bool expires,
            bool system,
            int targetID)
        {
            //Initialize response object
            JsonActionResponse response;
            try
            {
                //Create messages with params and add to database
                await _context.MessageCollection.AddAsync(new Message {
                    MessageTitle = title,
                    MessageContent = content,
                    MessageExpires = expires,
                    MessageSent = DateTime.Now,
                    MessageVisible = true,
                    SystemMessage = system,
                    SenderUser = await _context.UserCollection.SingleAsync(user => user.WindowsDirRef == User.Identity.Name),
                    ReceiverUser = await _context.UserCollection.FindAsync(targetID)
                });

                //Set response and save changes
                response = new JsonActionResponse(true);
                await _context.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                //Send unsuccessful, handle gracefully
                response = new JsonActionResponse(false);
                response.exceptionLog = String.Format("EXCEPTION OUTPUT: {0}", ex.ToString());
            }

            //Return
            return new JsonResult(JsonConvert.SerializeObject(response));
        }

        /// <summary>
        /// Fetch all messages for this user; AJAX powered.
        /// </summary>
        /// <returns></returns>
        public async Task<JsonResult> FetchMessages()
        {
            //Initialize response object
            MessageFetchResponse response;
            try
            {
                //Fetch messages from database, assign to JSON response
                response = new MessageFetchResponse(true);
                List<Message> userMessages = await _context.MessageCollection
                    .Include(message => message.ReceiverUser)
                    .Include(message => message.SenderUser)
                    .Where(message => message.ReceiverUser.WindowsDirRef == User.Identity.Name && message.MessageVisible)
                    .ToListAsync();
                foreach(Message thisMessage in userMessages)
                {
                    //Only add messages sent to this user and not marked as removed
                    MessageFetchResponse.MessageItem messageItem = new MessageFetchResponse.MessageItem(
                        thisMessage.ID,
                        thisMessage.MessageTitle,
                        thisMessage.MessageContent,
                        thisMessage.SystemMessage ? "System" : String.Format("{0}{1}", thisMessage.SenderUser.FirstName, thisMessage.SenderUser.SecondName),
                        String.Format("{0} at {1}", thisMessage.MessageSent.ToShortDateString(), thisMessage.MessageSent.ToShortTimeString()),
                        thisMessage.GetMessageExpiryDate());
                    response.messageList.Add(messageItem);
                }

                //Update response timestamp
                response.lastUpdate = DateTime.Now.ToShortTimeString();
            }
            catch (Exception ex)
            {
                //Fetch unsuccessful, handle gracefully
                response = new MessageFetchResponse(false);
                response.exceptionLog = String.Format("EXCEPTION OUTPUT: {0}", ex.ToString());
            }

            //Return
            return new JsonResult(JsonConvert.SerializeObject(response));
        }

        //Pseudo-delete a specific message
        public async Task<JsonResult> DeleteMessage(int id)
        {
            //Initialize response object
            JsonActionResponse response;
            try
            {
                //Remove message from the database
                response = new JsonActionResponse(true);
                Message thisMessage = await _context.MessageCollection.FindAsync(id);
                thisMessage.MessageVisible = false;
                _context.Update(thisMessage);
                await _context.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                //Removal unsuccessful, handle gracefully
                response = new JsonActionResponse(false);
                response.exceptionLog = String.Format("EXCEPTION OUTPUT: {0}", ex.ToString());
            }
            return new JsonResult(JsonConvert.SerializeObject(response));
        }
    }
}

STAX/Views/Shared/Components/Messages/Default.cshtml
@model STAX.Models.User

<!--VARS-->
@{
    List<STAX.Models.Message> allMessages = ViewBag.AllMessages;
    List<STAX.Models.User> allUsers = ViewBag.AllUsers;
}

<!--MESSAGES-->

<!--Main modal content-->
<div class="modal_fore">
    <p class="mainHeader">Messages</p>

    <!--Inbox Listing-->
    <div class="modal_multiPane" js-paneVal="0">
        <p class="subHeader" id="messages_lastUpdate">@String.Format("Inbox (Last Updated: {0})", DateTime.Now.ToShortTimeString())</p>
        <div id="messages_inbox" class="modal_scroller">
            @foreach (STAX.Models.Message thisMessage in allMessages)
            {
                var senderText = thisMessage.SystemMessage ? "From: System" : String.Format("{0} {1}", thisMessage.SenderUser.FirstName, thisMessage.SenderUser.SecondName);
                <div class="scrollItem">
                    <p class="header">Title: @thisMessage.MessageTitle</p>
                    <p class="header">From: @senderText</p>
                    <p class="header">Received: @String.Format("{0} at {1}", thisMessage.MessageSent.ToShortDateString(), thisMessage.MessageSent.ToShortTimeString())</p>
                    <p class="header">Expires: @thisMessage.GetMessageExpiryDate()</p>
                    <p>@thisMessage.MessageContent</p>
                    <br>
                    <div class="modal_option" title="Delete Message" js-messageID="@thisMessage.ID" onclick="DeleteMessage(this)">Delete</div>
                </div>
            }
        </div>
        <div class="modal_option" onclick="RetrieveMessages()" title="Refresh Inbox">Refresh</div>
    </div>

    <!--Message Composure-->
    <div class="modal_multiPane" js-paneVal="1">
        <form asp-controller="Message" asp-action="Create">
            <p class="subHeader">Compose</p>
            <br>
            <p class="subHeader">Send To</p>
            <select id="messages_targetInput">
                @foreach (STAX.Models.User thisUser in allUsers)
                {
                    <option value="@thisUser.ID">@String.Format("{0} {1}", thisUser.FirstName, thisUser.SecondName)</option>
                }
            </select>
            <p class="subHeader">Message Title</p>
            <input id="messages_titleInput" type="text" placeholder="Your message title." />

            <p class="subHeader">Message Content</p>
            <input id="messages_contentInput" type="text" placeholder="Your message text." />

            <div class="modal_option" title="Send Message" onclick="SendMessage()">Send</div>
        </form>
    </div>

    <!--Main options-->
    <br>
    <div class="modal_option" js-paneVal="0" onclick="SwitchPane(this)" title="View Messages">Inbox</div>
    @if(Model.UserPermissions.MessageAccessLevel == STAX.Models.UserPermissions.MessageAccessLevels.Read_And_Send)
    {
        <!--Gated access for message composition-->
        <div class="modal_option" js-paneVal="1" onclick="SwitchPane(this)" title="Write a Message">Compose</div>
    }
</div>